# Generated by Django 5.2 on 2025-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('no_of_bot', models.PositiveIntegerField()),
                ('no_query_per_bot', models.PositiveIntegerField()),
                ('no_of_docs_per_bot', models.PositiveIntegerField()),
                ('size_limit_per_docs', models.PositiveIntegerField(help_text='Size limit per document in units (e.g., MB)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
