# Generated by Django 5.2 on 2025-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0002_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='bot_id',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_id',
            field=models.CharField(default='TEMP01', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
