# Generated by Django 5.2 on 2025-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Plan pricing (e.g., in USD)', max_digits=8),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('limited', 'Limited'), ('private', 'Private'), ('personal', 'Personal')], default='public', max_length=20),
        ),
    ]
