# Generated by Django 5.2 on 2025-05-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0003_subscriptionplan_pricing_subscriptionplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanAlot',
            fields=[
                ('plan_alot_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('no_of_bot', models.PositiveIntegerField()),
                ('no_query', models.PositiveIntegerField()),
                ('no_of_docs', models.PositiveIntegerField()),
                ('doc_size_limit', models.PositiveIntegerField(help_text='Document size limit in MB')),
                ('expire_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_querySafe.user')),
            ],
        ),
    ]
