# Generated by Django 5.2 on 2025-05-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0004_userplanalot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanalot',
            name='plan_alot_id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userplanalot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_querySafe.user', to_field='user_id'),
        ),
    ]
