# Generated by Django 5.1.5 on 2025-05-15 06:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0005_alter_userplanalot_plan_alot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotdocument',
            name='document',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dipanshu Saini\\Desktop\\Metric Vibes\\Metric Vibes Tools\\Vertex AI\\AskVibes\\QuerySafe v0-2\\documents\\files_uploaded'), upload_to=''),
        ),
    ]
