# Generated by Django 5.2 on 2025-04-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0006_alter_chatbot_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotdocument',
            name='document',
            field=models.CharField(max_length=255),
        ),
    ]
