# Generated by Django 5.2 on 2025-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0008_chatbot_dataset_name_alter_chatbot_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(default='sdfasdfasdf', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
