# Generated by Django 5.2 on 2025-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0018_remove_activationcode_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('otp_verified', 'OTP Verified'), ('activated', 'Activated')], default='registered', max_length=20),
        ),
    ]
