# Generated by Django 5.2 on 2025-04-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0003_remove_chatbot_bot_id_chatbot_chatbot_id_chatbot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/chatbot/logos/'),
        ),
        migrations.CreateModel(
            name='ChatbotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='static/chatbot/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_askVibes.chatbot')),
            ],
        ),
    ]
