# Generated by Django 5.2 on 2025-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0005_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_logos/'),
        ),
    ]
