# Generated by Django 5.2 on 2025-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
