# Generated by Django 5.2 on 2025-05-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0015_alter_user_options_remove_user_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon_used',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
