# Generated by Django 5.2 on 2025-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_askVibes', '0017_activationcode_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcode',
            name='is_used',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
